-- This file is automatically generated


with

division as (
    select * from "IGI_PROD_DW"."dbo"."Division"
),

ordered as (
    select
        lDivisionKey,
        lSecurityBit,
        sCode,
        sDivision,
        sDivisionSearch,
        sCompanyCode,
        lDivisionContactKey,
        lFunctionalCurrencyKey,
        lTypeOfSettCurrencyMethod,
        lPresentationCurrencyKey,
        bMaintainSummaryIBNR,
        nPeerReviewUnderwritersReqd,
        sNotes,
        bCloseClaimAFP,
        bCannotPayClaimsLTR,
        bAllowOverridePolicyReference,
        bImmediateGeneratePolicyReference,
        dw_loadts,
        row_number() over (
            partition by
                lDivisionKey,
                lSecurityBit,
                sCode,
                sDivision,
                sDivisionSearch,
                sCompanyCode,
                lDivisionContactKey,
                lFunctionalCurrencyKey,
                lTypeOfSettCurrencyMethod,
                lPresentationCurrencyKey,
                bMaintainSummaryIBNR,
                nPeerReviewUnderwritersReqd,
                sNotes,
                bCloseClaimAFP,
                bCannotPayClaimsLTR,
                bAllowOverridePolicyReference,
                bImmediateGeneratePolicyReference
            order by
                dw_loadts
        ) as dw_extract_order
    from
        division
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lDivisionKey,
        lSecurityBit,
        sCode,
        sDivision,
        sDivisionSearch,
        sCompanyCode,
        lDivisionContactKey,
        lFunctionalCurrencyKey,
        lTypeOfSettCurrencyMethod,
        lPresentationCurrencyKey,
        bMaintainSummaryIBNR,
        nPeerReviewUnderwritersReqd,
        sNotes,
        bCloseClaimAFP,
        bCannotPayClaimsLTR,
        bAllowOverridePolicyReference,
        bImmediateGeneratePolicyReference,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lDivisionKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged