-- This file is automatically generated

with

type_of_accounting_element as (
    select * from "IGI_PROD_DW"."dbo"."TypeOfAccountingElement"
),

ordered as (
    select
        lTypeOfAccountingElementKey,
        sTypeOfAccountingElementCode,
        sTypeOfAccountingElement,
        sTypeOfAccountingElementSearch,
        lIncreaseDebitCreditKey,
        lDecreaseDebitCreditKey,
        dw_loadts,
        row_number() over (
            partition by
                lTypeOfAccountingElementKey,
                sTypeOfAccountingElementCode,
                sTypeOfAccountingElement,
                sTypeOfAccountingElementSearch,
                lIncreaseDebitCreditKey,
                lDecreaseDebitCreditKey
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_accounting_element
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lTypeOfAccountingElementKey,
        sTypeOfAccountingElementCode,
        sTypeOfAccountingElement,
        sTypeOfAccountingElementSearch,
        lIncreaseDebitCreditKey,
        lDecreaseDebitCreditKey,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lTypeOfAccountingElementKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged