-- This file is automatically generated



with

entity_state_members as (
    select * from "IGI_PROD_DW"."dbo"."ENTITYSTATEMEMBERS"
),

ordered as (
    select
        LENTITYSTATEMEMBERKEY,
        LENTITYSTATEKEY,
        SENTITYSTATEMEMBER,
        LICONKEY,
        BINITIAL,
        BDEFAULT,
        BACTIVE,
        NBIT,
        LTASKLISTKEY,
        BCREATABLE,
        MetadataIdentifier,
        lTargetEntityStateMemberKey,
        bUIEditAvailable,
        dw_loadts,
        row_number() over (
            partition by
                LENTITYSTATEMEMBERKEY,
                LENTITYSTATEKEY,
                SENTITYSTATEMEMBER,
                LICONKEY,
                BINITIAL,
                BDEFAULT,
                BACTIVE,
                NBIT,
                LTASKLISTKEY,
                BCREATABLE,
                MetadataIdentifier,
                lTargetEntityStateMemberKey,
                bUIEditAvailable
            order by
                dw_loadts
        ) as dw_extract_order
    from
        entity_state_members
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LENTITYSTATEMEMBERKEY,
        LENTITYSTATEKEY,
        SENTITYSTATEMEMBER,
        LICONKEY,
        BINITIAL,
        BDEFAULT,
        BACTIVE,
        NBIT,
        LTASKLISTKEY,
        BCREATABLE,
        MetadataIdentifier,
        lTargetEntityStateMemberKey,
        bUIEditAvailable,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LENTITYSTATEMEMBERKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged