-- This file is automatically generated


with

type_of_sub_class as (
    select * from "IGI_PROD_DW"."dbo"."TYPEOFSUBCLASS"
),

ordered as (
    select
        LTYPEOFSUBCLASSKEY,
        SSUBCLASS,
        SSUBCLASSSEARCH,
        sCode,
        sFSACoverage,
        sFSAAccountingClass,
        sFSARiskClass,
        lBlobCoverageSuffixKey,
        lBlobCoverageSummaryKey,
        bIsRCCCode,
        lTypeofCodeSetKey,
        bPeril,
        sControlIndex,
        sCoverageSuffix,
        sCoverageSummary,
        dw_loadts,
        row_number() over (
            partition by
                LTYPEOFSUBCLASSKEY,
                SSUBCLASS,
                SSUBCLASSSEARCH,
                sCode,
                sFSACoverage,
                sFSAAccountingClass,
                sFSARiskClass,
                lBlobCoverageSuffixKey,
                lBlobCoverageSummaryKey,
                bIsRCCCode,
                lTypeofCodeSetKey,
                bPeril,
                sControlIndex,
                sCoverageSuffix,
                sCoverageSummary
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_sub_class
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LTYPEOFSUBCLASSKEY,
        SSUBCLASS,
        SSUBCLASSSEARCH,
        sCode,
        sFSACoverage,
        sFSAAccountingClass,
        sFSARiskClass,
        lBlobCoverageSuffixKey,
        lBlobCoverageSummaryKey,
        bIsRCCCode,
        lTypeofCodeSetKey,
        bPeril,
        sControlIndex,
        sCoverageSuffix,
        sCoverageSummary,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LTYPEOFSUBCLASSKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged