-- This file is automatically generated

with

type_of_rag as (
    select * from "IGI_PROD_DW"."dbo"."TypeOfRAG"
),

ordered as (
    select
        lTypeOfRAGKey,
        sTypeofRAGCode,
        sTypeofRAGDescr,
        sSearchTypeofRAGDescr,
        dw_loadts,
        row_number() over (
            partition by
                lTypeOfRAGKey,
                sTypeofRAGCode,
                sTypeofRAGDescr,
                sSearchTypeofRAGDescr
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_rag
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lTypeOfRAGKey,
        sTypeofRAGCode,
        sTypeofRAGDescr,
        sSearchTypeofRAGDescr,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lTypeOfRAGKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged