-- This file is automatically generated



with

classification as (
    select * from "IGI_PROD_DW"."dbo"."Classification"
),

ordered as (
    select
        lClassificationKey,
        sClassificationCode,
        sClassificationDescr,
        sSearchClassificationDescr,
        lProductKey,
        dw_loadts,
        row_number() over (
            partition by
                lClassificationKey,
                sClassificationCode,
                sClassificationDescr,
                sSearchClassificationDescr,
                lProductKey
            order by
                dw_loadts
        ) as dw_extract_order
    from
        classification
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lClassificationKey,
        sClassificationCode,
        sClassificationDescr,
        sSearchClassificationDescr,
        lProductKey,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lClassificationKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged