create view "dbt_dev"."scd_zone_country__dbt_tmp" as
    -- This file is automatically generated


with

zone_country as (
    select * from "IGI_PROD_DW"."dbo"."ZoneCountry"
),

ordered as (
    select
        lCountryKey,
        sCountryCode,
        sCountry,
        sCountrySearch,
        bEUMember,
        sCountryCode2,
        bHasStates,
        bStateRequiredOnAddresses,
        bStateUsedInProductCarrier,
        lTypeOfStateNameKey,
        lTypeofCodeSetKey,
        lTaxDeptContactKey,
        bInEEA,
        LMAJORTERRITORYKEY,
        LTERRITORYKEY,
        LZONESOLVENCYREGIONKEY,
        BTERRITORY,
        lZoneCountryRiskKey,
        lZoneCountryLegalKey,
        bUKLegalCheck,
        bBermudaLegalCheck,
        dw_loadts,
        row_number() over (
            partition by
                lCountryKey,
                sCountryCode,
                sCountry,
                sCountrySearch,
                bEUMember,
                sCountryCode2,
                bHasStates,
                bStateRequiredOnAddresses,
                bStateUsedInProductCarrier,
                lTypeOfStateNameKey,
                lTypeofCodeSetKey,
                lTaxDeptContactKey,
                bInEEA,
                LMAJORTERRITORYKEY,
                LTERRITORYKEY,
                LZONESOLVENCYREGIONKEY,
                BTERRITORY,
                lZoneCountryRiskKey,
                lZoneCountryLegalKey,
                bUKLegalCheck,
                bBermudaLegalCheck
            order by
                dw_loadts
        ) as dw_extract_order
    from
        zone_country
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lCountryKey,
        sCountryCode,
        sCountry,
        sCountrySearch,
        bEUMember,
        sCountryCode2,
        bHasStates,
        bStateRequiredOnAddresses,
        bStateUsedInProductCarrier,
        lTypeOfStateNameKey,
        lTypeofCodeSetKey,
        lTaxDeptContactKey,
        bInEEA,
        LMAJORTERRITORYKEY,
        LTERRITORYKEY,
        LZONESOLVENCYREGIONKEY,
        BTERRITORY,
        lZoneCountryRiskKey,
        lZoneCountryLegalKey,
        bUKLegalCheck,
        bBermudaLegalCheck,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lCountryKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
