create view "dbt_dev"."scd_audit_state_transitions__dbt_tmp" as
    -- This file is automatically generated


with

audit_state_transitions as (
    select * from "IGI_PROD_DW"."dbo"."AUDITSTATETRANSITIONS"
),

ordered as (
    select
        LAUDITSTATETRANSITIONKEY,
        LENTITYKEY,
        LINSTANCEKEY,
        LENTITYSTATEACTIONKEY,
        LENTITYSTATEMEMBERKEY,
        LENTITYSTATEACTIONREASONKEY,
        LSECURITYUSERKEY,
        DTTRANSITION,
        dw_loadts,
        row_number() over (
            partition by
                LAUDITSTATETRANSITIONKEY,
                LENTITYKEY,
                LINSTANCEKEY,
                LENTITYSTATEACTIONKEY,
                LENTITYSTATEMEMBERKEY,
                LENTITYSTATEACTIONREASONKEY,
                LSECURITYUSERKEY,
                DTTRANSITION
            order by
                dw_loadts
        ) as dw_extract_order
    from
        audit_state_transitions
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LAUDITSTATETRANSITIONKEY,
        LENTITYKEY,
        LINSTANCEKEY,
        LENTITYSTATEACTIONKEY,
        LENTITYSTATEMEMBERKEY,
        LENTITYSTATEACTIONREASONKEY,
        LSECURITYUSERKEY,
        DTTRANSITION,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LAUDITSTATETRANSITIONKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
