create view "dbt_dev"."scd_type_of_placement__dbt_tmp" as
    -- This file is automatically generated

with

type_of_placement as (
    select * from "IGI_PROD_DW"."dbo"."TYPEOFPLACEMENT"
),

ordered as (
    select
        lTypeOfPlacementKey,
        sCode,
        sMOP,
        sMOPSearch,
        lTypeOfInsuranceKey,
        sRiskPrefix,
        bProportional,
        dw_loadts,
        row_number() over (
            partition by
                lTypeOfPlacementKey,
                sCode,
                sMOP,
                sMOPSearch,
                lTypeOfInsuranceKey,
                sRiskPrefix,
                bProportional
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_placement
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lTypeOfPlacementKey,
        sCode,
        sMOP,
        sMOPSearch,
        lTypeOfInsuranceKey,
        sRiskPrefix,
        bProportional,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lTypeOfPlacementKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
