create view "dbt_szammit"."scd_type_of_product_group__dbt_tmp" as
    -- This file is automatically generated


with

Type_Of_Product_Group as (
    select * from "IGI_PROD_DW"."dbo"."TypeOfProductGroup"
),

ordered as (
    select
        lTypeOfProductGroupKey,
        sCode,
        sProductGroup,
        sProductGroupSearch,
        dw_loadts,
        row_number() over (
            partition by
                lTypeOfProductGroupKey,
                sCode,
                sProductGroup,
                sProductGroupSearch,
                dw_loadts
                
            order by
                dw_loadts
        ) as dw_extract_order
    from
        Type_Of_Product_Group
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lTypeOfProductGroupKey,
        sCode,
        sProductGroup,
        sProductGroupSearch,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lTypeOfProductGroupKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
