create view "dbt_dev"."scd_contact_link__dbt_tmp" as
    -- This file is automatically generated


with

contact_link as (
    select * from "IGI_PROD_DW"."dbo"."CONTACTLINK"
),

ordered as (
    select
        LCONTACTLINKKEY,
        LCONTACTKEY,
        LLINKTOCONTACTKEY,
        LLINKKEY,
        bAllRoles,
        dw_loadts,
        row_number() over (
            partition by
                LCONTACTLINKKEY,
                LCONTACTKEY,
                LLINKTOCONTACTKEY,
                LLINKKEY,
                bAllRoles
            order by
                dw_loadts
        ) as dw_extract_order
    from
        contact_link
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LCONTACTLINKKEY,
        LCONTACTKEY,
        LLINKTOCONTACTKEY,
        LLINKKEY,
        bAllRoles,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LCONTACTLINKKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
