create view "dbt_szammit"."scd_journal_activity__dbt_tmp" as
    -- This file is automatically generated

with

journal_activity as (
    select * from "IGI_PROD_DW"."dbo"."JournalActivity"
),

ordered as (
    select
        lJournalActivityKey,
        lTemplateJournalActivityKey,
        lSourceEntityKey,
        lSourceInstanceKey,
        dtEntryDate,
        bUseAccountPeriodRates,
        lTemplateLossGainKey,
        dw_loadts,
        row_number() over (
            partition by
                lJournalActivityKey,
                lTemplateJournalActivityKey,
                lSourceEntityKey,
                lSourceInstanceKey,
                dtEntryDate,
                bUseAccountPeriodRates,
                lTemplateLossGainKey
            order by
                dw_loadts
        ) as dw_extract_order
    from
        journal_activity
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lJournalActivityKey,
        lTemplateJournalActivityKey,
        lSourceEntityKey,
        lSourceInstanceKey,
        dtEntryDate,
        bUseAccountPeriodRates,
        lTemplateLossGainKey,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lJournalActivityKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
