create view "dbt_szammit"."scd_ri_section_broker_security__dbt_tmp" as
    -- This file is automatically generated

with

ri_section_broker_security as (
    select * from "IGI_PROD_DW"."dbo"."RISectionBrokerSecurity"
),

ordered as (
    select
        lRISectionBrokerSecurityKey,
        lRISectionBrokerKey,
        lRISectionKey,
        lRIActivityKey,
        lRIPolicyKey,
        lRIFolderKey,
        lSecurityContactKey,
        bLeadReinsurer,
        lTypeOfRatingSourceKey,
        sSecurityRating,
        dProportionPc,
        dTreatyProportionPc,
        sSecurityReference,
        dOverridingCommissionPc,
        dCedingCommissionPc,
        dBrokerCommissionPc,
        nTermsOfTradeDays,
        dBrokerRemunerationPc,
        lRIGrossNetOfCommissionKey,
        dWrittenProportionPc,
        dw_loadts,
        row_number() over (
            partition by
                lRISectionBrokerSecurityKey,
                lRISectionBrokerKey,
                lRISectionKey,
                lRIActivityKey,
                lRIPolicyKey,
                lRIFolderKey,
                lSecurityContactKey,
                bLeadReinsurer,
                lTypeOfRatingSourceKey,
                sSecurityRating,
                dProportionPc,
                dTreatyProportionPc,
                sSecurityReference,
                dOverridingCommissionPc,
                dCedingCommissionPc,
                dBrokerCommissionPc,
                nTermsOfTradeDays,
                dBrokerRemunerationPc,
                lRIGrossNetOfCommissionKey,
                dWrittenProportionPc
            order by
                dw_loadts
        ) as dw_extract_order
    from
        ri_section_broker_security
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        lRISectionBrokerSecurityKey,
        lRISectionBrokerKey,
        lRISectionKey,
        lRIActivityKey,
        lRIPolicyKey,
        lRIFolderKey,
        lSecurityContactKey,
        bLeadReinsurer,
        lTypeOfRatingSourceKey,
        sSecurityRating,
        dProportionPc,
        dTreatyProportionPc,
        sSecurityReference,
        dOverridingCommissionPc,
        dCedingCommissionPc,
        dBrokerCommissionPc,
        nTermsOfTradeDays,
        dBrokerRemunerationPc,
        lRIGrossNetOfCommissionKey,
        dWrittenProportionPc,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by lRISectionBrokerSecurityKey order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
