create view "dbt_szammit"."scd_type_of_loss__dbt_tmp" as
    -- This file is automatically generated

with

type_of_loss as (
    select * from "IGI_PROD_DW"."dbo"."TYPEOFLOSS"
),

ordered as (
    select
        LTYPEOFLOSSKEY,
        STYPEOFLOSS,
        STYPEOFLOSSSEARCH,
        BPERIL,
        SISOLOSSDUEPERSONAL,
        SISOLOSSDUEPERSONALTEXAS,
        SISOLOSSDUECOMMERCIAL,
        SISOLOSSDUECOMMERCIALTEXAS,
        STRANSITISOLOSSDUEPERSONAL,
        STRANSITLOSSDUEPERSONALTEXAS,
        STRANSITISOLOSSDUECOMMERCIAL,
        STRANSITLOSSDUECOMMERCIALTEXAS,
        dw_loadts,
        row_number() over (
            partition by
                LTYPEOFLOSSKEY,
                STYPEOFLOSS,
                STYPEOFLOSSSEARCH,
                BPERIL,
                SISOLOSSDUEPERSONAL,
                SISOLOSSDUEPERSONALTEXAS,
                SISOLOSSDUECOMMERCIAL,
                SISOLOSSDUECOMMERCIALTEXAS,
                STRANSITISOLOSSDUEPERSONAL,
                STRANSITLOSSDUEPERSONALTEXAS,
                STRANSITISOLOSSDUECOMMERCIAL,
                STRANSITLOSSDUECOMMERCIALTEXAS
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_loss
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LTYPEOFLOSSKEY,
        STYPEOFLOSS,
        STYPEOFLOSSSEARCH,
        BPERIL,
        SISOLOSSDUEPERSONAL,
        SISOLOSSDUEPERSONALTEXAS,
        SISOLOSSDUECOMMERCIAL,
        SISOLOSSDUECOMMERCIALTEXAS,
        STRANSITISOLOSSDUEPERSONAL,
        STRANSITLOSSDUEPERSONALTEXAS,
        STRANSITISOLOSSDUECOMMERCIAL,
        STRANSITLOSSDUECOMMERCIALTEXAS,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LTYPEOFLOSSKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
