create view "dbt_szammit"."scd_type_of_ri_policy__dbt_tmp" as
    -- This file is automatically generated

with

type_of_ri_policy as (
    select * from "IGI_PROD_DW"."dbo"."TypeofRIPolicy"
),

ordered as (
    select
        LTYPEOFRIPOLICYKEY,
        SCODE,
        SPOLICYTYPE,
        SPOLICYTYPESEARCH,
        sRiskPrefix,
        dw_loadts,
        row_number() over (
            partition by
                LTYPEOFRIPOLICYKEY,
                SCODE,
                SPOLICYTYPE,
                SPOLICYTYPESEARCH,
                sRiskPrefix
            order by
                dw_loadts
        ) as dw_extract_order
    from
        type_of_ri_policy
),

filtered as (
    select * from ordered where dw_extract_order = 1
),

ranged as (
    select
        LTYPEOFRIPOLICYKEY,
        SCODE,
        SPOLICYTYPE,
        SPOLICYTYPESEARCH,
        sRiskPrefix,
        dw_loadts as _valid_from,
        lead(dw_loadts) over (partition by LTYPEOFRIPOLICYKEY order by dw_loadts) as _valid_to
    from
        filtered
)

select * from ranged
